env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go install github.com/tc-hib/go-winres@latest
    - go generate winres/init.go
    - go-winres init
    - go-winres make
release:
  draft: true
  discussion_category_name: General
builds:
  - id: nowin
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: '386'
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.go/u.Version=v{{.Version}}
  - id: win
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.go/u.Version=v{{.Version}}
